# manually triggered workflow, as releases to CRAN should not happen more often
# than once every few months.
on: workflow_dispatch

name: release-to-CRAN

jobs:
  upload:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-tinytex@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Release to CRAN
        run: |
          pkg <- devtools::as.package(".")
          built_path <- pkgbuild::build(pkg$path, tempdir(), manual = TRUE)
          devtools:::upload_cran(pkg, built_path)
        shell: Rscript {0}
